name: CAN Helper
version: "0.0.1"
slug: canHelper
description: "A background service to manage the CAN bus and provision new devices via MQTT."
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
hassio_api: true
privileged:
  - NET_ADMIN
udev: true
devices:
  - /dev/can0
services:
  - mqtt:need
options:
  can_interface: "can0"
  bitrate: 125000
  provisioning_topic_prefix: "can_helper"
schema:
  can_interface: str
  bitrate: int
  provisioning_topic_prefix: str
image: "ghcr.io/rgoskolkov/canhelper"
